name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:
    inputs:
      force_run_tests:
        description: 'Force run tests (true/false)'
        required: false
        default: 'false'

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out github repository
        id: github-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        if:
          (github.event.inputs.force_run_tests == 'true') ||
          (contains(steps.changed-files.outputs.all_changed_and_modified_files, 'packages/'))
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        id: install-node
        uses: actions/setup-node@v3
        if:
          (github.event.inputs.force_run_tests == 'true') ||
          (contains(steps.changed-files.outputs.all_changed_and_modified_files, 'packages/'))
        with:
          node-version: '16.x'

      - name: Install dependencies & build packages & compile contracts
        id: install-dependencies
        if:
          (github.event.inputs.force_run_tests == 'true') ||
          (contains(steps.changed-files.outputs.all_changed_and_modified_files, 'packages/'))
        run: yarn ; yarn build ; yarn compile
        env:
          BLOCK_NUMBER: 15946543
          NETWORK_FORK: 'mainnet'
          MAINNET_URL: ${{ secrets.MAINNET_URL }}

      - name: Run unit tests
        id: unit-test
        if:
          (github.event.inputs.force_run_tests == 'true') ||
          (contains(steps.changed-files.outputs.all_changed_and_modified_files, 'packages/'))
        run: yarn test
